export const pbk = `-----BEGIN PUBLIC KEY-----
MFswDQYJKoZIhvcNAQEBBQADSgAwRwJAXawJmJ0JSZ21Fm6BerzK8qyvg53Ss8Ux
Pxq3PReM824Dn1yVkMA0YR/J+9wz+xGvXAw6Y82sBpn+fpIM8Ho2FQIDAQAB
-----END PUBLIC KEY-----`;
